# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Thu Feb 19 06:26:03 2015
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1003, 652)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.hexColumn = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.hexColumn.setGeometry(QtCore.QRect(30, 80, 491, 331))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.hexColumn.setFont(font)
        self.hexColumn.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.hexColumn.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.hexColumn.setReadOnly(True)
        self.hexColumn.setObjectName("hexColumn")
        self.textColumn = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.textColumn.setGeometry(QtCore.QRect(520, 80, 221, 331))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.textColumn.setFont(font)
        self.textColumn.setReadOnly(True)
        self.textColumn.setObjectName("textColumn")
        self.actionCombo = QtWidgets.QComboBox(self.centralwidget)
        self.actionCombo.setGeometry(QtCore.QRect(30, 40, 81, 33))
        self.actionCombo.setObjectName("actionCombo")
        self.actionCombo.addItem("")
        self.actionCombo.addItem("")
        self.actionCombo.addItem("")
        self.actionCombo.addItem("")
        self.actionCombo.addItem("")
        self.actionCombo.addItem("")
        self.actionCombo.addItem("")
        self.actionCombo.addItem("")
        self.protoCombo = QtWidgets.QComboBox(self.centralwidget)
        self.protoCombo.setGeometry(QtCore.QRect(110, 40, 81, 33))
        self.protoCombo.setObjectName("protoCombo")
        self.protoCombo.addItem("")
        self.protoCombo.addItem("")
        self.protoCombo.addItem("")
        self.protoCombo.addItem("")
        self.srcCombo = QtWidgets.QComboBox(self.centralwidget)
        self.srcCombo.setGeometry(QtCore.QRect(190, 40, 131, 33))
        self.srcCombo.setObjectName("srcCombo")
        self.srcCombo.addItem("")
        self.srcPortCombo = QtWidgets.QComboBox(self.centralwidget)
        self.srcPortCombo.setGeometry(QtCore.QRect(320, 40, 81, 33))
        self.srcPortCombo.setObjectName("srcPortCombo")
        self.srcPortCombo.addItem("")
        self.dirCombo = QtWidgets.QComboBox(self.centralwidget)
        self.dirCombo.setGeometry(QtCore.QRect(400, 40, 61, 33))
        self.dirCombo.setObjectName("dirCombo")
        self.dirCombo.addItem("")
        self.dirCombo.addItem("")
        self.destCombo = QtWidgets.QComboBox(self.centralwidget)
        self.destCombo.setGeometry(QtCore.QRect(460, 40, 131, 33))
        self.destCombo.setObjectName("destCombo")
        self.destCombo.addItem("")
        self.destPortCombo = QtWidgets.QComboBox(self.centralwidget)
        self.destPortCombo.setGeometry(QtCore.QRect(590, 40, 81, 33))
        self.destPortCombo.setObjectName("destPortCombo")
        self.destPortCombo.addItem("")
        self.ruleText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.ruleText.setGeometry(QtCore.QRect(30, 550, 711, 31))
        self.ruleText.setObjectName("ruleText")
        self.packetBox = QtWidgets.QSpinBox(self.centralwidget)
        self.packetBox.setGeometry(QtCore.QRect(110, 0, 53, 33))
        self.packetBox.setObjectName("packetBox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 10, 41, 19))
        self.label.setObjectName("label")
        self.contentEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.contentEdit.setGeometry(QtCore.QRect(90, 460, 651, 33))
        self.contentEdit.setObjectName("contentEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 470, 60, 19))
        self.label_2.setObjectName("label_2")
        self.flowCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.flowCheck.setGeometry(QtCore.QRect(30, 430, 61, 23))
        self.flowCheck.setObjectName("flowCheck")
        self.flowCombo = QtWidgets.QComboBox(self.centralwidget)
        self.flowCombo.setEnabled(False)
        self.flowCombo.setGeometry(QtCore.QRect(90, 420, 111, 33))
        self.flowCombo.setObjectName("flowCombo")
        self.flowCombo.addItem("")
        self.flowCombo.addItem("")
        self.flowCombo.addItem("")
        self.flowCombo.addItem("")
        self.flowCombo.addItem("")
        self.flowCombo.addItem("")
        self.flowCombo.addItem("")
        self.flowCombo.addItem("")
        self.flowCombo.addItem("")
        self.flowCombo.addItem("")
        self.flowCombo.addItem("")
        self.streamButton = QtWidgets.QPushButton(self.centralwidget)
        self.streamButton.setEnabled(False)
        self.streamButton.setGeometry(QtCore.QRect(320, 0, 89, 35))
        self.streamButton.setObjectName("streamButton")
        self.depthCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.depthCheck.setGeometry(QtCore.QRect(30, 510, 71, 23))
        self.depthCheck.setObjectName("depthCheck")
        self.depthEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.depthEdit.setEnabled(False)
        self.depthEdit.setGeometry(QtCore.QRect(110, 500, 61, 33))
        self.depthEdit.setObjectName("depthEdit")
        self.offsetCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.offsetCheck.setGeometry(QtCore.QRect(180, 510, 81, 23))
        self.offsetCheck.setObjectName("offsetCheck")
        self.offsetEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.offsetEdit.setEnabled(False)
        self.offsetEdit.setGeometry(QtCore.QRect(260, 500, 61, 33))
        self.offsetEdit.setObjectName("offsetEdit")
        self.distanceCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.distanceCheck.setGeometry(QtCore.QRect(330, 510, 91, 23))
        self.distanceCheck.setObjectName("distanceCheck")
        self.distanceEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.distanceEdit.setEnabled(False)
        self.distanceEdit.setGeometry(QtCore.QRect(420, 500, 61, 33))
        self.distanceEdit.setObjectName("distanceEdit")
        self.withinCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.withinCheck.setGeometry(QtCore.QRect(490, 510, 93, 23))
        self.withinCheck.setObjectName("withinCheck")
        self.withinEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.withinEdit.setEnabled(False)
        self.withinEdit.setGeometry(QtCore.QRect(570, 500, 61, 33))
        self.withinEdit.setObjectName("withinEdit")
        self.nocaseCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.nocaseCheck.setGeometry(QtCore.QRect(640, 510, 93, 23))
        self.nocaseCheck.setObjectName("nocaseCheck")
        self.contentList = QtWidgets.QListWidget(self.centralwidget)
        self.contentList.setGeometry(QtCore.QRect(740, 80, 251, 331))
        self.contentList.setObjectName("contentList")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(740, 60, 91, 19))
        self.label_3.setObjectName("label_3")
        self.ruleRemoveButton = QtWidgets.QPushButton(self.centralwidget)
        self.ruleRemoveButton.setGeometry(QtCore.QRect(900, 410, 89, 35))
        self.ruleRemoveButton.setObjectName("ruleRemoveButton")
        self.addRuleButton = QtWidgets.QPushButton(self.centralwidget)
        self.addRuleButton.setGeometry(QtCore.QRect(810, 410, 89, 35))
        self.addRuleButton.setObjectName("addRuleButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1003, 31))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menu_File.addAction(self.actionOpen)
        self.menubar.addAction(self.menu_File.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Snort Rule Tool"))
        self.actionCombo.setCurrentText(_translate("MainWindow", "alert"))
        self.actionCombo.setItemText(0, _translate("MainWindow", "alert"))
        self.actionCombo.setItemText(1, _translate("MainWindow", "log"))
        self.actionCombo.setItemText(2, _translate("MainWindow", "pass"))
        self.actionCombo.setItemText(3, _translate("MainWindow", "activate"))
        self.actionCombo.setItemText(4, _translate("MainWindow", "dynamic"))
        self.actionCombo.setItemText(5, _translate("MainWindow", "drop"))
        self.actionCombo.setItemText(6, _translate("MainWindow", "reject"))
        self.actionCombo.setItemText(7, _translate("MainWindow", "sdrop"))
        self.protoCombo.setItemText(0, _translate("MainWindow", "tcp"))
        self.protoCombo.setItemText(1, _translate("MainWindow", "udp"))
        self.protoCombo.setItemText(2, _translate("MainWindow", "icmp"))
        self.protoCombo.setItemText(3, _translate("MainWindow", "ip"))
        self.srcCombo.setItemText(0, _translate("MainWindow", "any"))
        self.srcPortCombo.setItemText(0, _translate("MainWindow", "any"))
        self.dirCombo.setItemText(0, _translate("MainWindow", "->"))
        self.dirCombo.setItemText(1, _translate("MainWindow", "<->"))
        self.destCombo.setItemText(0, _translate("MainWindow", "any"))
        self.destPortCombo.setItemText(0, _translate("MainWindow", "any"))
        self.label.setText(_translate("MainWindow", "Packet"))
        self.label_2.setText(_translate("MainWindow", "Content"))
        self.flowCheck.setText(_translate("MainWindow", "Flow"))
        self.flowCombo.setItemText(0, _translate("MainWindow", "established"))
        self.flowCombo.setItemText(1, _translate("MainWindow", "to_client"))
        self.flowCombo.setItemText(2, _translate("MainWindow", "to_server"))
        self.flowCombo.setItemText(3, _translate("MainWindow", "from_client"))
        self.flowCombo.setItemText(4, _translate("MainWindow", "from_server"))
        self.flowCombo.setItemText(5, _translate("MainWindow", "not_established"))
        self.flowCombo.setItemText(6, _translate("MainWindow", "stateless"))
        self.flowCombo.setItemText(7, _translate("MainWindow", "no_stream"))
        self.flowCombo.setItemText(8, _translate("MainWindow", "only_stream"))
        self.flowCombo.setItemText(9, _translate("MainWindow", "no_frag"))
        self.flowCombo.setItemText(10, _translate("MainWindow", "only_frag"))
        self.streamButton.setText(_translate("MainWindow", "Build Stream"))
        self.depthCheck.setText(_translate("MainWindow", "Depth"))
        self.offsetCheck.setText(_translate("MainWindow", "Offset"))
        self.distanceCheck.setText(_translate("MainWindow", "Distance"))
        self.withinCheck.setText(_translate("MainWindow", "Within"))
        self.nocaseCheck.setText(_translate("MainWindow", "Nocase"))
        self.label_3.setText(_translate("MainWindow", "Content Rules"))
        self.ruleRemoveButton.setText(_translate("MainWindow", "Remove"))
        self.addRuleButton.setText(_translate("MainWindow", "Add"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.actionOpen.setText(_translate("MainWindow", "&Open"))

